0.0.19
pacstrapify: setup sysctl.conf and iptables
sshify: includes electrum verified authorized_keys setup

diff --git a/pacstrapit b/pacstrapit
--- a/pacstrapit
+++ b/pacstrapit
@@ -86,9 +86,18 @@ _user_name=live
 # user pass (strong)
 _user_pass=secret
 
+# ssh on/off (0 or 1)
+_ssh=0
+
+# ssh auth (caution)
+_electrum="https://raw.github.com/your/keys/master/id_electrum.pub"
+_electrum_version="1.9.7"
+_user_key="https://raw.github.com/your/keys/master/id_ed25519.pub"
+_user_key_sig="https://raw.github.com/your/keys/master/id_ed25519.pub.sig"
+_hosts_allowed="192.168.0."
+
 # debug on/off (0 or 1)
 _debug=1
-
 
 
 
@@ -120,17 +129,17 @@ if ! [[ "$UID" == '0' ]]; then exit 1; fi
 
 if ! [[ -x /usr/bin/expect ]]; then pacman -Sy expect --noconfirm; fi
 
+# depends: iptables
 
+                   if [[ "$_debug" == '1' ]]; then
+                     echo "*********************"
+                     echo "*                   *"
+                     echo "* depends: iptables *"
+                     echo "*                   *"
+                     echo "*********************"
+                                  fi
 
-
-# -----------------------------------------------------------------------------
-# functions: toc
-# -----------------------------------------------------------------------------
-
-# gdiskify
-# luksify
-# zramswapify
-# pacstrapify
+if ! [[ -x /usr/bin/iptables ]]; then pacman -Sy iptables --noconfirm; fi
 
 
 
@@ -701,23 +710,6 @@ fi
 arch-chroot /mnt sed -i 's!^HOOKS.*!HOOKS="base udev autodetect modconf block keyboard keymap encrypt btrfs filesystems shutdown usr"!' /etc/mkinitcpio.conf
 arch-chroot /mnt mkinitcpio -p linux
 
-# set sysctl.conf
-
-                   if [[ "$_debug" == '1' ]]; then
-                        echo "***************"
-                        echo "*             *"
-                        echo "* sysctl.conf *"
-                        echo "*             *"
-                        echo "***************"
-                                  fi
-
-if [[ "${_disk}" == 'ssd' ]]; then
-cat >> /mnt/etc/sysctl.conf <<'EOF'
-vm.swappiness=1
-vm.vfs_cache_pressure=50
-EOF
-fi
-
 # install grub
 
                    if [[ "$_debug" == '1' ]]; then
@@ -763,6 +755,186 @@ arch-chroot /mnt expect <<EOF
   expect eof
 EOF
 
+# set modprobe.conf
+
+                   if [[ "$_debug" == '1' ]]; then
+                       echo "*****************"
+                       echo "*               *"
+                       echo "* modprobe.conf *"
+                       echo "*               *"
+                       echo "*****************"
+                                  fi
+
+cat >> /mnt/etc/modprobe.d/modprobe.conf <<'EOF'
+alias floppy off
+blacklist fd0
+blacklist floppy
+blacklist bcma
+blacklist snd_pcsp
+blacklist pcspkr
+EOF
+
+# configure sysctl
+
+                   if [[ "$_debug" == '1' ]]; then
+                        echo "***************"
+                        echo "*             *"
+                        echo "* sysctl.conf *"
+                        echo "*             *"
+                        echo "***************"
+                                  fi
+
+cat > /mnt/etc/sysctl.conf <<'EOF'
+# Configuration file for runtime kernel parameters.
+# See sysctl.conf(5) for more information.
+
+# Have the CD-ROM close when you use it, and open when you are done.
+#dev.cdrom.autoclose = 1
+#dev.cdrom.autoeject = 1
+
+# Protection from the SYN flood attack.
+net.ipv4.tcp_syncookies = 1
+
+# See evil packets in your logs.
+net.ipv4.conf.all.log_martians = 1
+
+# Enables source route verification
+net.ipv4.conf.default.rp_filter = 1
+
+# Enable reverse path
+net.ipv4.conf.all.rp_filter = 1
+
+# Never accept redirects or source routes (these are only useful for routers).
+net.ipv4.conf.all.accept_redirects = 0
+net.ipv4.conf.all.accept_source_route = 0
+net.ipv6.conf.all.accept_redirects = 0
+net.ipv6.conf.all.accept_source_route = 0
+
+# Disable packet forwarding. Enable for openvpn.
+net.ipv4.ip_forward = 1
+net.ipv6.conf.default.forwarding = 1
+net.ipv6.conf.all.forwarding = 1
+
+# Ignore ICMP broadcasts
+net.ipv4.icmp_echo_ignore_broadcasts = 1
+
+# Drop ping packets
+net.ipv4.icmp_echo_ignore_all = 1
+
+# Protect against bad error messages
+net.ipv4.icmp_ignore_bogus_error_responses = 1
+
+# Tune IPv6
+net.ipv6.conf.default.router_solicitations = 0
+net.ipv6.conf.default.accept_ra_rtr_pref = 0
+net.ipv6.conf.default.accept_ra_pinfo = 0
+net.ipv6.conf.default.accept_ra_defrtr = 0
+net.ipv6.conf.default.autoconf = 0
+net.ipv6.conf.default.dad_transmits = 0
+net.ipv6.conf.default.max_addresses = 1
+
+# Increase the open file limit
+#fs.file-max = 65535
+
+# Allow for more PIDs (to reduce rollover problems);
+# may break some programs 32768
+#kernel.pid_max = 65536
+
+# Allow for fast recycling of TIME_WAIT sockets. Default value is 0
+# (disabled). Known to cause some issues with hoststated (load balancing
+# and fail over) if enabled, should be used with caution.
+net.ipv4.tcp_tw_recycle = 1
+# Allow for reusing sockets in TIME_WAIT state for new connections when
+# it's safe from protocol viewpoint. Default value is 0 (disabled).
+# Generally a safer alternative to tcp_tw_recycle.
+net.ipv4.tcp_tw_reuse = 1
+
+# Increase TCP max buffer size setable using setsockopt()
+#net.ipv4.tcp_rmem = 4096 87380 8388608
+#net.ipv4.tcp_wmem = 4096 87380 8388608
+
+# Increase Linux auto tuning TCP buffer limits
+# min, default, and max number of bytes to use
+# set max to at least 4MB, or higher if you use very high BDP paths
+#net.core.rmem_max = 8388608
+#net.core.wmem_max = 8388608
+#net.core.netdev_max_backlog = 5000
+#net.ipv4.tcp_window_scaling = 1
+
+# Tweak the port range used for outgoing connections.
+net.ipv4.ip_local_port_range = 2000 65535
+
+# Tweak those values to alter disk syncing and swap behavior.
+#vm.vfs_cache_pressure = 100
+#vm.laptop_mode = 0
+#vm.swappiness = 60
+
+# Tweak how the flow of kernel messages is throttled.
+#kernel.printk_ratelimit_burst = 10
+#kernel.printk_ratelimit = 5
+
+# Reboot 600 seconds after kernel panic or oops.
+#kernel.panic_on_oops = 1
+#kernel.panic = 600
+
+# Disable SysRq key to avoid console security issues.
+kernel.sysrq = 0
+EOF
+
+if [[ "${_disk}" == 'ssd' ]]; then
+  sed -i 's!^#vm.vfs_cache_pressure.*!vm.vfs_cache_pressure=50!' /mnt/etc/sysctl.conf
+  sed -i 's!^#vm.swappiness.*!vm.swappiness=1!' /mnt/etc/sysctl.conf
+fi
+
+arch-chroot /mnt sysctl -p
+
+# configure iptables
+
+                   if [[ "$_debug" == '1' ]]; then
+                         echo "************"
+                         echo "*          *"
+                         echo "* iptables *"
+                         echo "*          *"
+                         echo "************"
+                                  fi
+
+cat > /mnt/etc/iptables.test.rules <<'EOF'
+*filter
+#| Allow all loopback (lo0) traffic, and drop all traffic to 127/8 that doesn't use lo0
+-A INPUT -i lo -j ACCEPT
+-A INPUT ! -i lo -d 127.0.0.0/8 -j REJECT
+#| Allow all established inbound connections
+-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
+#| Allow all outbound traffic
+-A OUTPUT -j ACCEPT
+#| Allow HTTP and HTTPS connections
+-A INPUT -p tcp --dport 80 -j ACCEPT
+-A INPUT -p tcp --dport 443 -j ACCEPT
+#| Allow SSH connections
+-A INPUT -p tcp -m conntrack --ctstate NEW --dport 22 -j ACCEPT
+#| Allow ZeroMQ connections
+-A INPUT -p tcp -m conntrack --ctstate NEW --dport 4505 -j ACCEPT
+-A INPUT -p tcp -m conntrack --ctstate NEW --dport 4506 -j ACCEPT
+#| Allow NTP connections
+-I INPUT -p udp --dport 123 -j ACCEPT
+-I OUTPUT -p udp --sport 123 -j ACCEPT
+#| Reject pings
+-I INPUT -j DROP -p icmp --icmp-type echo-request
+#| Drop ident server
+-A INPUT -p tcp --dport ident -j DROP
+#| Log iptables denied calls
+-A INPUT -m limit --limit 15/minute -j LOG --log-prefix "[IPT]Dropped input: " --log-level 7
+-A OUTPUT -m limit --limit 15/minute -j LOG --log-prefix "[IPT]Dropped output: " --log-level 7
+#| Reject all other inbound - default deny unless explicitly allowed policy
+-A INPUT -j REJECT
+-A FORWARD -j REJECT
+COMMIT
+EOF
+iptables-save > /mnt/etc/iptables/iptables.up.rules
+iptables-restore < /mnt/etc/iptables/iptables.test.rules
+iptables-save > /mnt/etc/iptables/iptables.rules
+arch-chroot /mnt systemctl enable iptables
+
 # create user
 
                    if [[ "$_debug" == '1' ]]; then
@@ -807,26 +979,132 @@ EOF
                                   fi
 
 arch-chroot /mnt systemctl enable cronie
-arch-chroot /mnt systemctl enable zramswap
+}
 
-# set modprobe.conf
+
+
+
+# -----------------------------------------------------------------------------
+# sshify: setup ssh
+# -----------------------------------------------------------------------------
+
 
                    if [[ "$_debug" == '1' ]]; then
-                       echo "*****************"
-                       echo "*               *"
-                       echo "* modprobe.conf *"
-                       echo "*               *"
-                       echo "*****************"
+                         echo "************"
+                         echo "*  ------  *"
+                         echo "* |sshify| *"
+                         echo "*  ------  *"
+                         echo "************"
                                   fi
 
-cat >> /mnt/etc/modprobe.d/modprobe.conf <<'EOF'
-alias floppy off
-blacklist fd0
-blacklist floppy
-blacklist bcma
-blacklist snd_pcsp
-blacklist pcspkr
-EOF
+
+function sshify() {
+
+# configure sshd
+
+                   if [[ "$_debug" == '1' ]]; then
+                        echo "***************"
+                        echo "*             *"
+                        echo "* sshd_config *"
+                        echo "*             *"
+                        echo "***************"
+                                  fi
+
+sed -i 's!^#Port.*!Port 22!'                                                          /mnt/etc/ssh/sshd_config
+sed -i 's!^#Protocol.*!Protocol 2!'                                                   /mnt/etc/ssh/sshd_config
+sed -i 's!^#HostKey /etc/ssh/ssh_host_rsa_key!HostKey /etc/ssh/ssh_host_rsa_key!'     /mnt/etc/ssh/sshd_config
+sed -i 's!^#HostKey /etc/ssh/ssh_host_dsa_key!HostKey /etc/ssh/ssh_host_dsa_key!'     /mnt/etc/ssh/sshd_config
+sed -i 's!^#HostKey /etc/ssh/ssh_host_ecdsa_key!HostKey /etc/ssh/ssh_host_ecdsa_key!' /mnt/etc/ssh/sshd_config
+sed -i 's!^#SyslogFacility.*!SyslogFacility AUTH!'                                    /mnt/etc/ssh/sshd_config
+sed -i 's!^#LogLevel.*!LogLevel ERROR!'                                               /mnt/etc/ssh/sshd_config
+sed -i 's!^#LoginGraceTime.*!LoginGraceTime 2m!'                                      /mnt/etc/ssh/sshd_config
+sed -i 's!^#PermitRootLogin.*!PermitRootLogin no!'                                    /mnt/etc/ssh/sshd_config
+sed -i 's!^#StrictModes.*!StrictModes yes!'                                           /mnt/etc/ssh/sshd_config
+sed -i 's!^#PasswordAuthentication.*!PasswordAuthentication no!'                      /mnt/etc/ssh/sshd_config
+sed -i 's!^UsePAM yes!UsePAM no!'                                                     /mnt/etc/ssh/sshd_config
+sed -i 's!^#X11Forwarding.*!X11Forwarding no!'                                        /mnt/etc/ssh/sshd_config
+sed -i 's!^#X11DisplayOffset.*!X11DisplayOffset 10!'                                  /mnt/etc/ssh/sshd_config
+sed -i 's!^#PrintLastLog.*!PrintLastLog yes!'                                         /mnt/etc/ssh/sshd_config
+sed -i 's!^#TCPKeepAlive.*!TCPKeepAlive yes!'                                         /mnt/etc/ssh/sshd_config
+sed -i 's!^#UseDNS.*!UseDNS no!'                                                      /mnt/etc/ssh/sshd_config
+echo "AllowUsers ${_user_name}" >>                                                    /mnt/etc/ssh/sshd_config
+echo "sshd: ${_hosts_allowed}" >                                                      /mnt/etc/hosts.allow
+arch-chroot /mnt systemctl enable sshd
+
+# import keys
+
+                   if [[ "$_debug" == '1' ]]; then
+                        echo "***************"
+                        echo "*             *"
+                        echo "* import keys *"
+                        echo "*             *"
+                        echo "***************"
+                                  fi
+
+curl -k "${_electrum}"     -o ~/electrum.pub
+curl -k "${_user_key}"     -o ~/sshkey.pub
+curl -k "${_user_key_sig}" -o ~/sshkey.pub.sig
+
+# verify with electrum
+
+                   if [[ "$_debug" == '1' ]]; then
+                        echo "***************"
+                        echo "*             *"
+                        echo "* verify keys *"
+                        echo "*             *"
+                        echo "***************"
+                                  fi
+
+cd && curl -k https://codeload.github.com/spesmilo/{electrum}/{tar.gz}/{${_electrum_version}} -o "#1-#3.#2"
+tar xvzf electrum-${_electrum_version}.tar.gz
+cd electrum-${_electrum_version}
+find . -type f -print0 | xargs -0 sed -i 's#/usr/bin/python#/usr/bin/python2#g'
+find . -type f -print0 | xargs -0 sed -i 's#/usr/bin/env python#/usr/bin/env python2#g'
+_electrum_verified=$(./electrum verifymessage \
+                       "$(cat ~/electrum.pub)" \
+                       "$(cat ~/sshkey.pub.sig)" \
+                       "$(cat ~/sshkey.pub)")
+
+# setup authorized_keys
+
+                   if [[ "$_debug" == '1' ]]; then
+                      echo "*******************"
+                      echo "*                 *"
+                      echo "* authorized_keys *"
+                      echo "*                 *"
+                      echo "*******************"
+                                  fi
+
+if [[ "${_electrum_verified}" == 'true' ]]; then
+  mkdir -p /home/${_user_name}/.ssh
+  chmod 700 /home/${_user_name}/.ssh
+  cat ~/sshkey.pub /home/${_user_name}/.ssh/authorized_keys
+  chmod 600 /home/${_user_name}/.ssh/authorized_keys
+  chown -R ${_user_name}:users /home/${_user_name}/.ssh
+else
+  echo "Electrum verification code rejected."
+  exit 1
+fi
+}
+
+
+
+
+# -----------------------------------------------------------------------------
+# debugify: debug
+# -----------------------------------------------------------------------------
+
+
+                   if [[ "$_debug" == '1' ]]; then
+                        echo "**************"
+                        echo "*  -------   *"
+                        echo "* |debugify| *"
+                        echo "*  -------   *"
+                        echo "**************"
+                                  fi
+
+
+function debugify() {
 
 # debug
 
@@ -838,34 +1116,52 @@ EOF
                            echo "*********"
                                   fi
 
-if [[ "$_debug" == '1' ]]; then
-  echo "cat /boot/grub/grub.cfg:"
-  arch-chroot /mnt cat /boot/grub/grub.cfg
-  echo "cat /etc/fstab:"
-  arch-chroot /mnt cat /etc/fstab
-  echo "cat /etc/hostname:"
-  arch-chroot /mnt cat /etc/hostname
-  echo "cat /etc/locale.conf:"
-  arch-chroot /mnt cat /etc/locale.conf
-  echo "cat /etc/locale.gen:"
-  arch-chroot /mnt cat /etc/locale.gen
-  echo "cat /etc/mkinitcpio.conf:"
-  arch-chroot /mnt cat /etc/mkinitcpio.conf
-  echo "cat /etc/modprobe.d/modprobe.conf:"
-  arch-chroot /mnt cat /etc/modprobe.d/modprobe.conf
-  echo "cat /etc/resolv.conf.head:"
-  arch-chroot /mnt cat /etc/resolv.conf.head
-  echo "cat /etc/sysctl.conf:"
-  arch-chroot /mnt cat /etc/sysctl.conf
-  echo "cat /etc/systemd/sleep.conf:"
-  arch-chroot /mnt cat /etc/systemd/sleep.conf
-  echo "cat /etc/vconsole.conf:"
-  arch-chroot /mnt cat /etc/vconsole.conf
-  echo "ls -laiF /home/${_user_name}:"
-  arch-chroot /mnt ls -laiF /home/${_user_name}
-  echo "systemctl list-unit-files:"
-  arch-chroot /mnt systemctl list-unit-files | perl -p -e 'print while (<>)'
-fi
+echo "cat /boot/grub/grub.cfg:"
+arch-chroot /mnt cat /boot/grub/grub.cfg
+echo "cat /etc/fstab:"
+arch-chroot /mnt cat /etc/fstab
+echo "cat /etc/hostname:"
+arch-chroot /mnt cat /etc/hostname
+echo "cat /etc/locale.conf:"
+arch-chroot /mnt cat /etc/locale.conf
+echo "cat /etc/locale.gen:"
+arch-chroot /mnt cat /etc/locale.gen
+echo "cat /etc/mkinitcpio.conf:"
+arch-chroot /mnt cat /etc/mkinitcpio.conf
+echo "cat /etc/modprobe.d/modprobe.conf:"
+arch-chroot /mnt cat /etc/modprobe.d/modprobe.conf
+echo "cat /etc/resolv.conf.head:"
+arch-chroot /mnt cat /etc/resolv.conf.head
+echo "cat /etc/sysctl.conf:"
+arch-chroot /mnt cat /etc/sysctl.conf
+echo "cat /etc/systemd/sleep.conf:"
+arch-chroot /mnt cat /etc/systemd/sleep.conf
+echo "cat /etc/vconsole.conf:"
+arch-chroot /mnt cat /etc/vconsole.conf
+echo "ls -laiF /home/${_user_name}:"
+arch-chroot /mnt ls -laiF /home/${_user_name}
+echo "systemctl list-unit-files:"
+arch-chroot /mnt systemctl list-unit-files | perl -p -e 'print while (<>)'
+}
+
+
+
+
+# -----------------------------------------------------------------------------
+# exitify: exit pacstrapit
+# -----------------------------------------------------------------------------
+
+
+                   if [[ "$_debug" == '1' ]]; then
+                         echo "*************"
+                         echo "*  -------  *"
+                         echo "* |exitify| *"
+                         echo "*  -------  *"
+                         echo "*************"
+                                  fi
+
+
+function exitify() {
 
 # exit pacstrapped chroot
 
@@ -878,6 +1174,12 @@ fi
                                   fi
 
 umount /mnt/{boot,home,opt,srv,tmp,usr,var,}
+
+echo "******************************"
+echo "*                            *"
+echo "* Maybe time for a reboot... *"
+echo "*                            *"
+echo "******************************"
 }
 
 
@@ -891,9 +1193,6 @@ gdiskify
 luksify
 zramswapify
 pacstrapify
-
-echo "******************************"
-echo "*                            *"
-echo "* Maybe time for a reboot... *"
-echo "*                            *"
-echo "******************************"
+if [[ "${_ssh}" == '1' ]]; then sshify; fi
+if [[ "${_debug}" == '1' ]]; then debugify; fi
+exitify
